#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# export PATH=$PATH:~/$PYTHON/virtenv/bin/
# export PYTHON_EGG_CACHE=~/$PYTHON/virtenv/lib/python2.7/site-packages
export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python-2.6/virtenv/lib/python-2.6/site-packages

# source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
# source ~/$PYTHON/virtenv/bin/activate
source $OPENSHIFT_HOMEDIR/python-2.7/virtenv/bin/activate

echo "CDing into '$OPENSHIFT_REPO_DIR/wsgi'"
cd $OPENSHIFT_REPO_DIR/wsgi

echo "Executing 'python manage.py syncdb --noinput'"
python manage.py syncdb --noinput
 
echo "Executing 'python manage.py collectstatic --noinput -v0'"
python manage.py collectstatic --noinput -v0
