#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

export PATH=$PATH:${OPENSHIFT_HOMEDIR}python/virtenv/bin/
export PYTHON_EGG_CACHE=${OPENSHIFT_HOMEDIR}python/virtenv/lib/python-2.7/site-packages

source ${OPENSHIFT_HOMEDIR}python/virtenv/bin/activate

# source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

# echo "CDing into '$OPENSHIFT_REPO_DIR/wsgi'"
# cd ${OPENSHIFT_REPO_DIR}wsgi

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py migrate'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py migrate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py collectstatic --noinput'"
cd $OPENSHIFT_REPO_DIR
python wsgi/manage.py collectstatic --noinput
cp -afr static_temp/admin static/admin
